stages:
  - build

build:
  stage: build
  before_script:
    - mkdir -p ./ci-reports
  image: openjdk:8
  script:
    - pwd
    - ls
    - chmod +x /home/build/gradlew
    - chmod a+w /usr/bin
    - sudo -u build /home/build/gradlew clean build
  artifacts:
    when: always
    expire_in: 3d
    paths:
      - ./build/libs
      - ./build/reports
