stages:
  - build
  - package
  - deploy

cache:
  # Per-branch caching
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle

build:
  stage: build
  before_script:
    # This should help to enable gradle cache
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - mkdir -p ./ci-reports
  image: openjdk:8
  script:
    - chmod +x gradlew
    - chmod a+w /usr/bin
    - build gradlew clean build
  artifacts:
    when: always
    expire_in: 3d
    paths:
      - ./build/libs
      - ./build/reports
