image: gradle:alpine

before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

stages:
- build
- test

build:
  stage: build
  script:
  - ./gradlew --build-cache assemble
  when: manual

test:
  stage: test
  script:
  - ./gradlew check
  when: manual


