image: gradle:alpine

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test

build:
  stage: build
  script:
  - ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    when: always
    expire_in: 3d
    paths:
      - ./build/libs
      - ./build/reports
  when: manual

test:
  stage: test
  script: .
  - /gradlew check
  artifacts:
    when: always
    expire_in: 3d
    paths:
    - ./build/libs
    - ./build/reports
  when: manual


