server:
    port: 8110
spring:
    application:
        name: ProjektBus-Server
    data:
        mongodb:
#            uri: mongodb+srv://test:y52InmyjQkw7RnDe@projektbus-1sqzc.gcp.mongodb.net/test?retryWrites=true
            database: ProjektBus
            port: 0
