server:
    port: 8110
    ssl:
        enabled: true
        key-store: classpath:keystore/projektbus.jks
        key-store-password: 'projekt'
        key-password: 'projekt'
        keyAlias: projektbus
        key-store-type: jks
spring:
    application:
        name: ProjektBus-Server
    data:
        mongodb:
            uri: mongodb+srv://test:y52InmyjQkw7RnDe@projektbus-1sqzc.gcp.mongodb.net/test?retryWrites=true
            database: ProjektBus